version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DATABASE=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5435:5432"
  redis:
    image: redis
    ports:
      - "6382:6379"
