version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=development
      - POSTGRES_DATABASE=development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
  redis:
    image: redis
    ports:
      - "6380:6379"
